---
- name: creating docker mounts for grafana
  file:
    path: "{{ docker_vol_mount_dir }}/grafana"
    owner: "472"
    state: directory

- name: creating docker mounts for prometheus
  file:
    path: "{{ docker_vol_mount_dir }}/prometheus"
    owner: "65534"
    state: directory

- name: deploy prometheus config
  template:
    src: prometheus.yml.j2
    dest: /data/prometheus.yml
    mode: "65534"
  # TODO: restart of prometheus container if changed

- name: deploy startup script
  template:
    src: grafana-prometheus.sh.j2
    dest: /tmp/grafana-prometheus.sh
    mode: "0755"

- name: configure firewall
  firewalld:
    service: http
    permanent: yes
    state: enabled
