language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

# Use the new container infrastructure
sudo: false

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

script:
  # Basic syntax check
  - ansible-playbook site.yml -i hosts --syntax-check
  - ansible -i hosts -m debug -a 'var=hostvars[inventory_hostname]' all
