---
- name: create a logical volumes on {{ data_vg_name }}
  lvol:
    vg: "{{ data_vg_name }}"
    lv: "{{ item.name }}"
    size: "{{ item.size }}"
  loop: "{{ lv_config }}"

- name: create a xfs filesystem on logical volumes
  filesystem:
    fstype: xfs
    dev: "/dev/{{ data_vg_name }}/{{ item.name }}"
  loop: "{{ lv_config }}"

- name: mount path to logical volume
  become: "{{ become | default('yes') }}"
  mount:
    path: "{{ item.path }}"
    src: "/dev/{{ data_vg_name }}/{{ item.name }}"
    fstype: xfs
    state: mounted
  loop: "{{ lv_config }}"

- name: change ownership of directory if required
  file:
    path: "{{ item.path }}"
    owner: "{{ lv_config.uid | string }}"
  when: item.uid | default('') != ''
  loop: "{{ lv_config }}"
