---
- name: reload NetworkManager
  service:
    name: NetworkManager
    state: reloaded

- name: restart node_exporter
  service:
    name: node_exporter
    state: restarted

- name: reload firewalld
  service:
    name: firewalld
    state: reloaded
