---
- name: get user with uid 1000
  getent:
    database: passwd
    key: "1000"

- name: change ownership of {{ jenkins_home }}
  file:
    path: "{{ jenkins_home }}"
    owner: "{{ lookup('dict', getent_passwd).key }}"

- name: deploy Jenkins Master startup script
  template:
    src: jenkins.sh.j2
    dest: /tmp/jenkins.sh
    mode: "0755"
  when: '"slave" not in inventory_hostname'

- name: deploy Jenkins Agent startup script
  template:
    src: jenkins-agent.sh.j2
    dest: /tmp/jenkins.sh
    mode: "0755"
  when: '"slave" in inventory_hostname'

- name: deploy npmrc file
  template:
    src: npmrc.j2
    dest: "{{ jenkins_home }}/.npmrc"
    mode: "700"
    owner: "1000"
  when: '"slave" in inventory_hostname'

- name: configure firewall
  firewalld:
    service: http
    permanent: yes
    state: enabled
