---
- name: copy artifactory startup script
  copy:
    src: artifactory.sh
    dest: "/tmp/artifactory.sh"
    mode: 0755

- name: copy nginx config
  copy:
    src: nginx
    dest: "{{ docker_vol_mount_dir }}"
- file:
    path: "{{ docker_vol_mount_dir }}/nginx/conf.d"
    state: directory
- template:
    src: artifactory.conf.j2
    dest: "{{ docker_vol_mount_dir }}/nginx/conf.d/artifactory.conf"
    backup: yes

- name: create directories for docker volume mounts
  file:
    path: "{{ docker_vol_mount_dir }}/{{ item }}"
    state: directory
  loop:
    - artifactory
    - postgresql

- name: create user with uid 1030 if it does not exists.
  import_tasks: create-user-by-uid.yml
  vars:
    uid: "1030"
    uname: artifactory

- name: changing ownership of {{ docker_vol_mount_dir }}/artifactory
  file:
    path: "{{ docker_vol_mount_dir }}/artifactory"
    owner: "1030"
    state: directory

- name: configure firewall
  firewalld:
    service: http
    permanent: yes
    state: enabled
